# fly.toml app configuration file generated for open-saas-wasp-sh-client on 2023-12-04T12:34:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "open-saas-wasp-sh-client"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.http_options.response]
  pristine = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
