---
name: Template Release

'on':
  push:
    tags:
      - 'wasp-v*-template'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create template archive
        working-directory: template
        run: tar -czf ../template.tar.gz .

      - name: Create draft release if it doesn't exist
        run: |
          if ! gh release view "${GITHUB_REF_NAME}"; then
            gh release create "${GITHUB_REF_NAME}" --draft
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        run: gh release upload "${GITHUB_REF_NAME}" template.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
