---
name: Template Release

'on':
  push:
    tags:
      - 'wasp-v*-template'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create template archive
        run: |
          cd template
          tar -czf ../open-saas-template-${GITHUB_REF_NAME}.tar.gz .

      - name: Upload release asset
        run: |
          gh release upload ${GITHUB_REF_NAME} \
            open-saas-template-${GITHUB_REF_NAME}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
